name: Deploy Documentation
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Build Documentation
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install MkDocs dependencies
        run: |
          pip install mkdocs-material
          pip install pillow cairosvg
      - name: Build documentation
        run: mkdocs build
      
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site
          destination_dir: .
          force_orphan: true 
